[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
    'cd ../..',
    'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm turbo run build --filter=web']

[start]
cmd = 'cd apps/web && pnpm start'